version: "3.8"

services:
   fr-api:
      build:
         context: .
         dockerfile: Dockerfile
      container_name: fr-api
      restart: unless-stopped
      ports:
         - "8000:8000"
      volumes:
         - ./api/output:/app/api/output
         - ./api/temp:/app/api/temp
         - ./models:/app/models
      environment:
         - MODEL_PATH=/app/models
         - LOG_LEVEL=INFO
         - MAX_WORKERS=4
      healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:8000/"]
         interval: 30s
         timeout: 10s
         retries: 3
         start_period: 40s

   fr-web:
      build:
         context: ./web
         dockerfile: Dockerfile
      container_name: fr-web
      restart: unless-stopped
      ports:
         - "80:80"
      depends_on:
         - fr-api
      environment:
         - API_URL=http://fr-api:8000

volumes:
   fr-api-output:
   fr-api-temp:
   fr-models:
